// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p3.proto

package io.github.portlek.synergy.proto;

public final class P3 {
  private P3() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface P3MetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.github.portlek.synergy.proto.P3Meta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string version = 2;</code>
     * @return The version.
     */
    java.lang.String getVersion();
    /**
     * <code>string version = 2;</code>
     * @return The bytes for version.
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>bool promoted = 3;</code>
     * @return The promoted.
     */
    boolean getPromoted();
  }
  /**
   * Protobuf type {@code io.github.portlek.synergy.proto.P3Meta}
   */
  public static final class P3Meta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.github.portlek.synergy.proto.P3Meta)
      P3MetaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use P3Meta.newBuilder() to construct.
    private P3Meta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private P3Meta() {
      id_ = "";
      version_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new P3Meta();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private P3Meta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 24: {

              promoted_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.portlek.synergy.proto.P3.internal_static_io_github_portlek_synergy_proto_P3Meta_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.portlek.synergy.proto.P3.internal_static_io_github_portlek_synergy_proto_P3Meta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.portlek.synergy.proto.P3.P3Meta.class, io.github.portlek.synergy.proto.P3.P3Meta.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private volatile java.lang.Object version_;
    /**
     * <code>string version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 2;</code>
     * @return The bytes for version.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROMOTED_FIELD_NUMBER = 3;
    private boolean promoted_;
    /**
     * <code>bool promoted = 3;</code>
     * @return The promoted.
     */
    @java.lang.Override
    public boolean getPromoted() {
      return promoted_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
      }
      if (promoted_ != false) {
        output.writeBool(3, promoted_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
      }
      if (promoted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, promoted_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.portlek.synergy.proto.P3.P3Meta)) {
        return super.equals(obj);
      }
      io.github.portlek.synergy.proto.P3.P3Meta other = (io.github.portlek.synergy.proto.P3.P3Meta) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getVersion()
          .equals(other.getVersion())) return false;
      if (getPromoted()
          != other.getPromoted()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + PROMOTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPromoted());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.portlek.synergy.proto.P3.P3Meta parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.portlek.synergy.proto.P3.P3Meta parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.portlek.synergy.proto.P3.P3Meta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.portlek.synergy.proto.P3.P3Meta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.portlek.synergy.proto.P3.P3Meta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.portlek.synergy.proto.P3.P3Meta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.portlek.synergy.proto.P3.P3Meta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.portlek.synergy.proto.P3.P3Meta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.portlek.synergy.proto.P3.P3Meta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.portlek.synergy.proto.P3.P3Meta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.portlek.synergy.proto.P3.P3Meta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.portlek.synergy.proto.P3.P3Meta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.portlek.synergy.proto.P3.P3Meta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.github.portlek.synergy.proto.P3Meta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.github.portlek.synergy.proto.P3Meta)
        io.github.portlek.synergy.proto.P3.P3MetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.portlek.synergy.proto.P3.internal_static_io_github_portlek_synergy_proto_P3Meta_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.portlek.synergy.proto.P3.internal_static_io_github_portlek_synergy_proto_P3Meta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.portlek.synergy.proto.P3.P3Meta.class, io.github.portlek.synergy.proto.P3.P3Meta.Builder.class);
      }

      // Construct using io.github.portlek.synergy.proto.P3.P3Meta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        version_ = "";

        promoted_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.portlek.synergy.proto.P3.internal_static_io_github_portlek_synergy_proto_P3Meta_descriptor;
      }

      @java.lang.Override
      public io.github.portlek.synergy.proto.P3.P3Meta getDefaultInstanceForType() {
        return io.github.portlek.synergy.proto.P3.P3Meta.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.portlek.synergy.proto.P3.P3Meta build() {
        io.github.portlek.synergy.proto.P3.P3Meta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.portlek.synergy.proto.P3.P3Meta buildPartial() {
        io.github.portlek.synergy.proto.P3.P3Meta result = new io.github.portlek.synergy.proto.P3.P3Meta(this);
        result.id_ = id_;
        result.version_ = version_;
        result.promoted_ = promoted_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.portlek.synergy.proto.P3.P3Meta) {
          return mergeFrom((io.github.portlek.synergy.proto.P3.P3Meta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.portlek.synergy.proto.P3.P3Meta other) {
        if (other == io.github.portlek.synergy.proto.P3.P3Meta.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (other.getPromoted() != false) {
          setPromoted(other.getPromoted());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.portlek.synergy.proto.P3.P3Meta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.portlek.synergy.proto.P3.P3Meta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>string version = 2;</code>
       * @return The version.
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string version = 2;</code>
       * @return The bytes for version.
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 2;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2;</code>
       * @param value The bytes for version to set.
       * @return This builder for chaining.
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private boolean promoted_ ;
      /**
       * <code>bool promoted = 3;</code>
       * @return The promoted.
       */
      @java.lang.Override
      public boolean getPromoted() {
        return promoted_;
      }
      /**
       * <code>bool promoted = 3;</code>
       * @param value The promoted to set.
       * @return This builder for chaining.
       */
      public Builder setPromoted(boolean value) {
        
        promoted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool promoted = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPromoted() {
        
        promoted_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.github.portlek.synergy.proto.P3Meta)
    }

    // @@protoc_insertion_point(class_scope:io.github.portlek.synergy.proto.P3Meta)
    private static final io.github.portlek.synergy.proto.P3.P3Meta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.portlek.synergy.proto.P3.P3Meta();
    }

    public static io.github.portlek.synergy.proto.P3.P3Meta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<P3Meta>
        PARSER = new com.google.protobuf.AbstractParser<P3Meta>() {
      @java.lang.Override
      public P3Meta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new P3Meta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<P3Meta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<P3Meta> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.portlek.synergy.proto.P3.P3Meta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PackageDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.github.portlek.synergy.proto.PackageData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
     * @return Whether the meta field is set.
     */
    boolean hasMeta();
    /**
     * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
     * @return The meta.
     */
    io.github.portlek.synergy.proto.P3.P3Meta getMeta();
    /**
     * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
     */
    io.github.portlek.synergy.proto.P3.P3MetaOrBuilder getMetaOrBuilder();

    /**
     * <code>string checksum = 3;</code>
     * @return The checksum.
     */
    java.lang.String getChecksum();
    /**
     * <code>string checksum = 3;</code>
     * @return The bytes for checksum.
     */
    com.google.protobuf.ByteString
        getChecksumBytes();

    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code io.github.portlek.synergy.proto.PackageData}
   */
  public static final class PackageData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.github.portlek.synergy.proto.PackageData)
      PackageDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PackageData.newBuilder() to construct.
    private PackageData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PackageData() {
      checksum_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PackageData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PackageData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.github.portlek.synergy.proto.P3.P3Meta.Builder subBuilder = null;
              if (meta_ != null) {
                subBuilder = meta_.toBuilder();
              }
              meta_ = input.readMessage(io.github.portlek.synergy.proto.P3.P3Meta.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(meta_);
                meta_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              checksum_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.portlek.synergy.proto.P3.internal_static_io_github_portlek_synergy_proto_PackageData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.portlek.synergy.proto.P3.internal_static_io_github_portlek_synergy_proto_PackageData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.portlek.synergy.proto.P3.PackageData.class, io.github.portlek.synergy.proto.P3.PackageData.Builder.class);
    }

    public static final int META_FIELD_NUMBER = 1;
    private io.github.portlek.synergy.proto.P3.P3Meta meta_;
    /**
     * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
     * @return Whether the meta field is set.
     */
    @java.lang.Override
    public boolean hasMeta() {
      return meta_ != null;
    }
    /**
     * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
     * @return The meta.
     */
    @java.lang.Override
    public io.github.portlek.synergy.proto.P3.P3Meta getMeta() {
      return meta_ == null ? io.github.portlek.synergy.proto.P3.P3Meta.getDefaultInstance() : meta_;
    }
    /**
     * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
     */
    @java.lang.Override
    public io.github.portlek.synergy.proto.P3.P3MetaOrBuilder getMetaOrBuilder() {
      return getMeta();
    }

    public static final int CHECKSUM_FIELD_NUMBER = 3;
    private volatile java.lang.Object checksum_;
    /**
     * <code>string checksum = 3;</code>
     * @return The checksum.
     */
    @java.lang.Override
    public java.lang.String getChecksum() {
      java.lang.Object ref = checksum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        checksum_ = s;
        return s;
      }
    }
    /**
     * <code>string checksum = 3;</code>
     * @return The bytes for checksum.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChecksumBytes() {
      java.lang.Object ref = checksum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checksum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (meta_ != null) {
        output.writeMessage(1, getMeta());
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      if (!getChecksumBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, checksum_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (meta_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMeta());
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (!getChecksumBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, checksum_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.portlek.synergy.proto.P3.PackageData)) {
        return super.equals(obj);
      }
      io.github.portlek.synergy.proto.P3.PackageData other = (io.github.portlek.synergy.proto.P3.PackageData) obj;

      if (hasMeta() != other.hasMeta()) return false;
      if (hasMeta()) {
        if (!getMeta()
            .equals(other.getMeta())) return false;
      }
      if (!getChecksum()
          .equals(other.getChecksum())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMeta()) {
        hash = (37 * hash) + META_FIELD_NUMBER;
        hash = (53 * hash) + getMeta().hashCode();
      }
      hash = (37 * hash) + CHECKSUM_FIELD_NUMBER;
      hash = (53 * hash) + getChecksum().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.portlek.synergy.proto.P3.PackageData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.portlek.synergy.proto.P3.PackageData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.portlek.synergy.proto.P3.PackageData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.portlek.synergy.proto.P3.PackageData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.portlek.synergy.proto.P3.PackageData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.portlek.synergy.proto.P3.PackageData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.portlek.synergy.proto.P3.PackageData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.portlek.synergy.proto.P3.PackageData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.portlek.synergy.proto.P3.PackageData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.portlek.synergy.proto.P3.PackageData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.portlek.synergy.proto.P3.PackageData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.portlek.synergy.proto.P3.PackageData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.portlek.synergy.proto.P3.PackageData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.github.portlek.synergy.proto.PackageData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.github.portlek.synergy.proto.PackageData)
        io.github.portlek.synergy.proto.P3.PackageDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.portlek.synergy.proto.P3.internal_static_io_github_portlek_synergy_proto_PackageData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.portlek.synergy.proto.P3.internal_static_io_github_portlek_synergy_proto_PackageData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.portlek.synergy.proto.P3.PackageData.class, io.github.portlek.synergy.proto.P3.PackageData.Builder.class);
      }

      // Construct using io.github.portlek.synergy.proto.P3.PackageData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (metaBuilder_ == null) {
          meta_ = null;
        } else {
          meta_ = null;
          metaBuilder_ = null;
        }
        checksum_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.portlek.synergy.proto.P3.internal_static_io_github_portlek_synergy_proto_PackageData_descriptor;
      }

      @java.lang.Override
      public io.github.portlek.synergy.proto.P3.PackageData getDefaultInstanceForType() {
        return io.github.portlek.synergy.proto.P3.PackageData.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.portlek.synergy.proto.P3.PackageData build() {
        io.github.portlek.synergy.proto.P3.PackageData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.portlek.synergy.proto.P3.PackageData buildPartial() {
        io.github.portlek.synergy.proto.P3.PackageData result = new io.github.portlek.synergy.proto.P3.PackageData(this);
        if (metaBuilder_ == null) {
          result.meta_ = meta_;
        } else {
          result.meta_ = metaBuilder_.build();
        }
        result.checksum_ = checksum_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.portlek.synergy.proto.P3.PackageData) {
          return mergeFrom((io.github.portlek.synergy.proto.P3.PackageData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.portlek.synergy.proto.P3.PackageData other) {
        if (other == io.github.portlek.synergy.proto.P3.PackageData.getDefaultInstance()) return this;
        if (other.hasMeta()) {
          mergeMeta(other.getMeta());
        }
        if (!other.getChecksum().isEmpty()) {
          checksum_ = other.checksum_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.portlek.synergy.proto.P3.PackageData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.portlek.synergy.proto.P3.PackageData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private io.github.portlek.synergy.proto.P3.P3Meta meta_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.portlek.synergy.proto.P3.P3Meta, io.github.portlek.synergy.proto.P3.P3Meta.Builder, io.github.portlek.synergy.proto.P3.P3MetaOrBuilder> metaBuilder_;
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       * @return Whether the meta field is set.
       */
      public boolean hasMeta() {
        return metaBuilder_ != null || meta_ != null;
      }
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       * @return The meta.
       */
      public io.github.portlek.synergy.proto.P3.P3Meta getMeta() {
        if (metaBuilder_ == null) {
          return meta_ == null ? io.github.portlek.synergy.proto.P3.P3Meta.getDefaultInstance() : meta_;
        } else {
          return metaBuilder_.getMessage();
        }
      }
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       */
      public Builder setMeta(io.github.portlek.synergy.proto.P3.P3Meta value) {
        if (metaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          meta_ = value;
          onChanged();
        } else {
          metaBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       */
      public Builder setMeta(
          io.github.portlek.synergy.proto.P3.P3Meta.Builder builderForValue) {
        if (metaBuilder_ == null) {
          meta_ = builderForValue.build();
          onChanged();
        } else {
          metaBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       */
      public Builder mergeMeta(io.github.portlek.synergy.proto.P3.P3Meta value) {
        if (metaBuilder_ == null) {
          if (meta_ != null) {
            meta_ =
              io.github.portlek.synergy.proto.P3.P3Meta.newBuilder(meta_).mergeFrom(value).buildPartial();
          } else {
            meta_ = value;
          }
          onChanged();
        } else {
          metaBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       */
      public Builder clearMeta() {
        if (metaBuilder_ == null) {
          meta_ = null;
          onChanged();
        } else {
          meta_ = null;
          metaBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       */
      public io.github.portlek.synergy.proto.P3.P3Meta.Builder getMetaBuilder() {
        
        onChanged();
        return getMetaFieldBuilder().getBuilder();
      }
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       */
      public io.github.portlek.synergy.proto.P3.P3MetaOrBuilder getMetaOrBuilder() {
        if (metaBuilder_ != null) {
          return metaBuilder_.getMessageOrBuilder();
        } else {
          return meta_ == null ?
              io.github.portlek.synergy.proto.P3.P3Meta.getDefaultInstance() : meta_;
        }
      }
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.portlek.synergy.proto.P3.P3Meta, io.github.portlek.synergy.proto.P3.P3Meta.Builder, io.github.portlek.synergy.proto.P3.P3MetaOrBuilder> 
          getMetaFieldBuilder() {
        if (metaBuilder_ == null) {
          metaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.github.portlek.synergy.proto.P3.P3Meta, io.github.portlek.synergy.proto.P3.P3Meta.Builder, io.github.portlek.synergy.proto.P3.P3MetaOrBuilder>(
                  getMeta(),
                  getParentForChildren(),
                  isClean());
          meta_ = null;
        }
        return metaBuilder_;
      }

      private java.lang.Object checksum_ = "";
      /**
       * <code>string checksum = 3;</code>
       * @return The checksum.
       */
      public java.lang.String getChecksum() {
        java.lang.Object ref = checksum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          checksum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string checksum = 3;</code>
       * @return The bytes for checksum.
       */
      public com.google.protobuf.ByteString
          getChecksumBytes() {
        java.lang.Object ref = checksum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          checksum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string checksum = 3;</code>
       * @param value The checksum to set.
       * @return This builder for chaining.
       */
      public Builder setChecksum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        checksum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string checksum = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChecksum() {
        
        checksum_ = getDefaultInstance().getChecksum();
        onChanged();
        return this;
      }
      /**
       * <code>string checksum = 3;</code>
       * @param value The bytes for checksum to set.
       * @return This builder for chaining.
       */
      public Builder setChecksumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        checksum_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.github.portlek.synergy.proto.PackageData)
    }

    // @@protoc_insertion_point(class_scope:io.github.portlek.synergy.proto.PackageData)
    private static final io.github.portlek.synergy.proto.P3.PackageData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.portlek.synergy.proto.P3.PackageData();
    }

    public static io.github.portlek.synergy.proto.P3.PackageData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PackageData>
        PARSER = new com.google.protobuf.AbstractParser<PackageData>() {
      @java.lang.Override
      public PackageData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PackageData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PackageData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PackageData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.portlek.synergy.proto.P3.PackageData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SplitPackageDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.github.portlek.synergy.proto.SplitPackageData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
     * @return Whether the meta field is set.
     */
    boolean hasMeta();
    /**
     * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
     * @return The meta.
     */
    io.github.portlek.synergy.proto.P3.P3Meta getMeta();
    /**
     * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
     */
    io.github.portlek.synergy.proto.P3.P3MetaOrBuilder getMetaOrBuilder();

    /**
     * <code>string checksum = 2;</code>
     * @return The checksum.
     */
    java.lang.String getChecksum();
    /**
     * <code>string checksum = 2;</code>
     * @return The bytes for checksum.
     */
    com.google.protobuf.ByteString
        getChecksumBytes();

    /**
     * <code>bool endOfFile = 3;</code>
     * @return The endOfFile.
     */
    boolean getEndOfFile();

    /**
     * <code>uint32 chunkCount = 4;</code>
     * @return The chunkCount.
     */
    int getChunkCount();

    /**
     * <code>uint32 chunkId = 5;</code>
     * @return The chunkId.
     */
    int getChunkId();

    /**
     * <code>bytes data = 6;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code io.github.portlek.synergy.proto.SplitPackageData}
   */
  public static final class SplitPackageData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.github.portlek.synergy.proto.SplitPackageData)
      SplitPackageDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SplitPackageData.newBuilder() to construct.
    private SplitPackageData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SplitPackageData() {
      checksum_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SplitPackageData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SplitPackageData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.github.portlek.synergy.proto.P3.P3Meta.Builder subBuilder = null;
              if (meta_ != null) {
                subBuilder = meta_.toBuilder();
              }
              meta_ = input.readMessage(io.github.portlek.synergy.proto.P3.P3Meta.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(meta_);
                meta_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              checksum_ = s;
              break;
            }
            case 24: {

              endOfFile_ = input.readBool();
              break;
            }
            case 32: {

              chunkCount_ = input.readUInt32();
              break;
            }
            case 40: {

              chunkId_ = input.readUInt32();
              break;
            }
            case 50: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.portlek.synergy.proto.P3.internal_static_io_github_portlek_synergy_proto_SplitPackageData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.portlek.synergy.proto.P3.internal_static_io_github_portlek_synergy_proto_SplitPackageData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.portlek.synergy.proto.P3.SplitPackageData.class, io.github.portlek.synergy.proto.P3.SplitPackageData.Builder.class);
    }

    public static final int META_FIELD_NUMBER = 1;
    private io.github.portlek.synergy.proto.P3.P3Meta meta_;
    /**
     * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
     * @return Whether the meta field is set.
     */
    @java.lang.Override
    public boolean hasMeta() {
      return meta_ != null;
    }
    /**
     * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
     * @return The meta.
     */
    @java.lang.Override
    public io.github.portlek.synergy.proto.P3.P3Meta getMeta() {
      return meta_ == null ? io.github.portlek.synergy.proto.P3.P3Meta.getDefaultInstance() : meta_;
    }
    /**
     * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
     */
    @java.lang.Override
    public io.github.portlek.synergy.proto.P3.P3MetaOrBuilder getMetaOrBuilder() {
      return getMeta();
    }

    public static final int CHECKSUM_FIELD_NUMBER = 2;
    private volatile java.lang.Object checksum_;
    /**
     * <code>string checksum = 2;</code>
     * @return The checksum.
     */
    @java.lang.Override
    public java.lang.String getChecksum() {
      java.lang.Object ref = checksum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        checksum_ = s;
        return s;
      }
    }
    /**
     * <code>string checksum = 2;</code>
     * @return The bytes for checksum.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChecksumBytes() {
      java.lang.Object ref = checksum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checksum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDOFFILE_FIELD_NUMBER = 3;
    private boolean endOfFile_;
    /**
     * <code>bool endOfFile = 3;</code>
     * @return The endOfFile.
     */
    @java.lang.Override
    public boolean getEndOfFile() {
      return endOfFile_;
    }

    public static final int CHUNKCOUNT_FIELD_NUMBER = 4;
    private int chunkCount_;
    /**
     * <code>uint32 chunkCount = 4;</code>
     * @return The chunkCount.
     */
    @java.lang.Override
    public int getChunkCount() {
      return chunkCount_;
    }

    public static final int CHUNKID_FIELD_NUMBER = 5;
    private int chunkId_;
    /**
     * <code>uint32 chunkId = 5;</code>
     * @return The chunkId.
     */
    @java.lang.Override
    public int getChunkId() {
      return chunkId_;
    }

    public static final int DATA_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 6;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (meta_ != null) {
        output.writeMessage(1, getMeta());
      }
      if (!getChecksumBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, checksum_);
      }
      if (endOfFile_ != false) {
        output.writeBool(3, endOfFile_);
      }
      if (chunkCount_ != 0) {
        output.writeUInt32(4, chunkCount_);
      }
      if (chunkId_ != 0) {
        output.writeUInt32(5, chunkId_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(6, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (meta_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMeta());
      }
      if (!getChecksumBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, checksum_);
      }
      if (endOfFile_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, endOfFile_);
      }
      if (chunkCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, chunkCount_);
      }
      if (chunkId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, chunkId_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.portlek.synergy.proto.P3.SplitPackageData)) {
        return super.equals(obj);
      }
      io.github.portlek.synergy.proto.P3.SplitPackageData other = (io.github.portlek.synergy.proto.P3.SplitPackageData) obj;

      if (hasMeta() != other.hasMeta()) return false;
      if (hasMeta()) {
        if (!getMeta()
            .equals(other.getMeta())) return false;
      }
      if (!getChecksum()
          .equals(other.getChecksum())) return false;
      if (getEndOfFile()
          != other.getEndOfFile()) return false;
      if (getChunkCount()
          != other.getChunkCount()) return false;
      if (getChunkId()
          != other.getChunkId()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMeta()) {
        hash = (37 * hash) + META_FIELD_NUMBER;
        hash = (53 * hash) + getMeta().hashCode();
      }
      hash = (37 * hash) + CHECKSUM_FIELD_NUMBER;
      hash = (53 * hash) + getChecksum().hashCode();
      hash = (37 * hash) + ENDOFFILE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEndOfFile());
      hash = (37 * hash) + CHUNKCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getChunkCount();
      hash = (37 * hash) + CHUNKID_FIELD_NUMBER;
      hash = (53 * hash) + getChunkId();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.portlek.synergy.proto.P3.SplitPackageData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.portlek.synergy.proto.P3.SplitPackageData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.portlek.synergy.proto.P3.SplitPackageData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.portlek.synergy.proto.P3.SplitPackageData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.portlek.synergy.proto.P3.SplitPackageData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.portlek.synergy.proto.P3.SplitPackageData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.portlek.synergy.proto.P3.SplitPackageData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.portlek.synergy.proto.P3.SplitPackageData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.portlek.synergy.proto.P3.SplitPackageData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.portlek.synergy.proto.P3.SplitPackageData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.portlek.synergy.proto.P3.SplitPackageData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.portlek.synergy.proto.P3.SplitPackageData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.portlek.synergy.proto.P3.SplitPackageData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.github.portlek.synergy.proto.SplitPackageData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.github.portlek.synergy.proto.SplitPackageData)
        io.github.portlek.synergy.proto.P3.SplitPackageDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.portlek.synergy.proto.P3.internal_static_io_github_portlek_synergy_proto_SplitPackageData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.portlek.synergy.proto.P3.internal_static_io_github_portlek_synergy_proto_SplitPackageData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.portlek.synergy.proto.P3.SplitPackageData.class, io.github.portlek.synergy.proto.P3.SplitPackageData.Builder.class);
      }

      // Construct using io.github.portlek.synergy.proto.P3.SplitPackageData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (metaBuilder_ == null) {
          meta_ = null;
        } else {
          meta_ = null;
          metaBuilder_ = null;
        }
        checksum_ = "";

        endOfFile_ = false;

        chunkCount_ = 0;

        chunkId_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.portlek.synergy.proto.P3.internal_static_io_github_portlek_synergy_proto_SplitPackageData_descriptor;
      }

      @java.lang.Override
      public io.github.portlek.synergy.proto.P3.SplitPackageData getDefaultInstanceForType() {
        return io.github.portlek.synergy.proto.P3.SplitPackageData.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.portlek.synergy.proto.P3.SplitPackageData build() {
        io.github.portlek.synergy.proto.P3.SplitPackageData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.portlek.synergy.proto.P3.SplitPackageData buildPartial() {
        io.github.portlek.synergy.proto.P3.SplitPackageData result = new io.github.portlek.synergy.proto.P3.SplitPackageData(this);
        if (metaBuilder_ == null) {
          result.meta_ = meta_;
        } else {
          result.meta_ = metaBuilder_.build();
        }
        result.checksum_ = checksum_;
        result.endOfFile_ = endOfFile_;
        result.chunkCount_ = chunkCount_;
        result.chunkId_ = chunkId_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.portlek.synergy.proto.P3.SplitPackageData) {
          return mergeFrom((io.github.portlek.synergy.proto.P3.SplitPackageData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.portlek.synergy.proto.P3.SplitPackageData other) {
        if (other == io.github.portlek.synergy.proto.P3.SplitPackageData.getDefaultInstance()) return this;
        if (other.hasMeta()) {
          mergeMeta(other.getMeta());
        }
        if (!other.getChecksum().isEmpty()) {
          checksum_ = other.checksum_;
          onChanged();
        }
        if (other.getEndOfFile() != false) {
          setEndOfFile(other.getEndOfFile());
        }
        if (other.getChunkCount() != 0) {
          setChunkCount(other.getChunkCount());
        }
        if (other.getChunkId() != 0) {
          setChunkId(other.getChunkId());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.portlek.synergy.proto.P3.SplitPackageData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.portlek.synergy.proto.P3.SplitPackageData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private io.github.portlek.synergy.proto.P3.P3Meta meta_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.portlek.synergy.proto.P3.P3Meta, io.github.portlek.synergy.proto.P3.P3Meta.Builder, io.github.portlek.synergy.proto.P3.P3MetaOrBuilder> metaBuilder_;
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       * @return Whether the meta field is set.
       */
      public boolean hasMeta() {
        return metaBuilder_ != null || meta_ != null;
      }
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       * @return The meta.
       */
      public io.github.portlek.synergy.proto.P3.P3Meta getMeta() {
        if (metaBuilder_ == null) {
          return meta_ == null ? io.github.portlek.synergy.proto.P3.P3Meta.getDefaultInstance() : meta_;
        } else {
          return metaBuilder_.getMessage();
        }
      }
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       */
      public Builder setMeta(io.github.portlek.synergy.proto.P3.P3Meta value) {
        if (metaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          meta_ = value;
          onChanged();
        } else {
          metaBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       */
      public Builder setMeta(
          io.github.portlek.synergy.proto.P3.P3Meta.Builder builderForValue) {
        if (metaBuilder_ == null) {
          meta_ = builderForValue.build();
          onChanged();
        } else {
          metaBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       */
      public Builder mergeMeta(io.github.portlek.synergy.proto.P3.P3Meta value) {
        if (metaBuilder_ == null) {
          if (meta_ != null) {
            meta_ =
              io.github.portlek.synergy.proto.P3.P3Meta.newBuilder(meta_).mergeFrom(value).buildPartial();
          } else {
            meta_ = value;
          }
          onChanged();
        } else {
          metaBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       */
      public Builder clearMeta() {
        if (metaBuilder_ == null) {
          meta_ = null;
          onChanged();
        } else {
          meta_ = null;
          metaBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       */
      public io.github.portlek.synergy.proto.P3.P3Meta.Builder getMetaBuilder() {
        
        onChanged();
        return getMetaFieldBuilder().getBuilder();
      }
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       */
      public io.github.portlek.synergy.proto.P3.P3MetaOrBuilder getMetaOrBuilder() {
        if (metaBuilder_ != null) {
          return metaBuilder_.getMessageOrBuilder();
        } else {
          return meta_ == null ?
              io.github.portlek.synergy.proto.P3.P3Meta.getDefaultInstance() : meta_;
        }
      }
      /**
       * <code>.io.github.portlek.synergy.proto.P3Meta meta = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.github.portlek.synergy.proto.P3.P3Meta, io.github.portlek.synergy.proto.P3.P3Meta.Builder, io.github.portlek.synergy.proto.P3.P3MetaOrBuilder> 
          getMetaFieldBuilder() {
        if (metaBuilder_ == null) {
          metaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.github.portlek.synergy.proto.P3.P3Meta, io.github.portlek.synergy.proto.P3.P3Meta.Builder, io.github.portlek.synergy.proto.P3.P3MetaOrBuilder>(
                  getMeta(),
                  getParentForChildren(),
                  isClean());
          meta_ = null;
        }
        return metaBuilder_;
      }

      private java.lang.Object checksum_ = "";
      /**
       * <code>string checksum = 2;</code>
       * @return The checksum.
       */
      public java.lang.String getChecksum() {
        java.lang.Object ref = checksum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          checksum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string checksum = 2;</code>
       * @return The bytes for checksum.
       */
      public com.google.protobuf.ByteString
          getChecksumBytes() {
        java.lang.Object ref = checksum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          checksum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string checksum = 2;</code>
       * @param value The checksum to set.
       * @return This builder for chaining.
       */
      public Builder setChecksum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        checksum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string checksum = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearChecksum() {
        
        checksum_ = getDefaultInstance().getChecksum();
        onChanged();
        return this;
      }
      /**
       * <code>string checksum = 2;</code>
       * @param value The bytes for checksum to set.
       * @return This builder for chaining.
       */
      public Builder setChecksumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        checksum_ = value;
        onChanged();
        return this;
      }

      private boolean endOfFile_ ;
      /**
       * <code>bool endOfFile = 3;</code>
       * @return The endOfFile.
       */
      @java.lang.Override
      public boolean getEndOfFile() {
        return endOfFile_;
      }
      /**
       * <code>bool endOfFile = 3;</code>
       * @param value The endOfFile to set.
       * @return This builder for chaining.
       */
      public Builder setEndOfFile(boolean value) {
        
        endOfFile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool endOfFile = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndOfFile() {
        
        endOfFile_ = false;
        onChanged();
        return this;
      }

      private int chunkCount_ ;
      /**
       * <code>uint32 chunkCount = 4;</code>
       * @return The chunkCount.
       */
      @java.lang.Override
      public int getChunkCount() {
        return chunkCount_;
      }
      /**
       * <code>uint32 chunkCount = 4;</code>
       * @param value The chunkCount to set.
       * @return This builder for chaining.
       */
      public Builder setChunkCount(int value) {
        
        chunkCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 chunkCount = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearChunkCount() {
        
        chunkCount_ = 0;
        onChanged();
        return this;
      }

      private int chunkId_ ;
      /**
       * <code>uint32 chunkId = 5;</code>
       * @return The chunkId.
       */
      @java.lang.Override
      public int getChunkId() {
        return chunkId_;
      }
      /**
       * <code>uint32 chunkId = 5;</code>
       * @param value The chunkId to set.
       * @return This builder for chaining.
       */
      public Builder setChunkId(int value) {
        
        chunkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 chunkId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearChunkId() {
        
        chunkId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 6;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 6;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.github.portlek.synergy.proto.SplitPackageData)
    }

    // @@protoc_insertion_point(class_scope:io.github.portlek.synergy.proto.SplitPackageData)
    private static final io.github.portlek.synergy.proto.P3.SplitPackageData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.portlek.synergy.proto.P3.SplitPackageData();
    }

    public static io.github.portlek.synergy.proto.P3.SplitPackageData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SplitPackageData>
        PARSER = new com.google.protobuf.AbstractParser<SplitPackageData>() {
      @java.lang.Override
      public SplitPackageData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SplitPackageData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SplitPackageData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SplitPackageData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.portlek.synergy.proto.P3.SplitPackageData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_portlek_synergy_proto_P3Meta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_portlek_synergy_proto_P3Meta_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_portlek_synergy_proto_PackageData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_portlek_synergy_proto_PackageData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_portlek_synergy_proto_SplitPackageData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_portlek_synergy_proto_SplitPackageData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010p3.proto\022\037io.github.portlek.synergy.pr" +
      "oto\"7\n\006P3Meta\022\n\n\002id\030\001 \001(\t\022\017\n\007version\030\002 \001" +
      "(\t\022\020\n\010promoted\030\003 \001(\010\"d\n\013PackageData\0225\n\004m" +
      "eta\030\001 \001(\0132\'.io.github.portlek.synergy.pr" +
      "oto.P3Meta\022\020\n\010checksum\030\003 \001(\t\022\014\n\004data\030\002 \001" +
      "(\014\"\241\001\n\020SplitPackageData\0225\n\004meta\030\001 \001(\0132\'." +
      "io.github.portlek.synergy.proto.P3Meta\022\020" +
      "\n\010checksum\030\002 \001(\t\022\021\n\tendOfFile\030\003 \001(\010\022\022\n\nc" +
      "hunkCount\030\004 \001(\r\022\017\n\007chunkId\030\005 \001(\r\022\014\n\004data" +
      "\030\006 \001(\014B\006B\002P3H\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_github_portlek_synergy_proto_P3Meta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_github_portlek_synergy_proto_P3Meta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_portlek_synergy_proto_P3Meta_descriptor,
        new java.lang.String[] { "Id", "Version", "Promoted", });
    internal_static_io_github_portlek_synergy_proto_PackageData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_github_portlek_synergy_proto_PackageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_portlek_synergy_proto_PackageData_descriptor,
        new java.lang.String[] { "Meta", "Checksum", "Data", });
    internal_static_io_github_portlek_synergy_proto_SplitPackageData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_github_portlek_synergy_proto_SplitPackageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_portlek_synergy_proto_SplitPackageData_descriptor,
        new java.lang.String[] { "Meta", "Checksum", "EndOfFile", "ChunkCount", "ChunkId", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
