name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: |
          mvn install -Pcheckstyle
          mvn test -Pcoverage jacoco:report

      - uses: codecov/codecov-action@v1.0.14

      - uses: actions/upload-artifact@v2
        with:
          name: synergy
          path: target/Synergy.jar
